language: node_js
branches:
  only:
  - develop
node_js:
- '10'
before_script:
- chmod +x ./scripts/deploy.sh
script: "./scripts/deploy.sh"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  local_dir: tmp
  on:
    branch: develop
env:
  global:
    secure: hyQy4FM+RSxZOnZrC2He/evlDNfDjpRRlP8OrGRZUdhD9IhvuW3b+MDeuDYmiaTDKpg47zVFWkf/6CSENij0P80MCxs4QCp17Ph4n5OvmHW37vuBC5FrYJKdm0TDqFeBdEOg4A7b6hUiphjFuR6ikvHQDgT7dsPzwuTb+wbpMLwIscUbKXK6QZyEDZUxS/uyLOlXwlRGAxJbiq6LC8OQocasxSy8KjOJc8vwYZi7oCIONhUfheOK0U8HdhUoKQSmgDdNkE1Uy3Jwyd5FNQtxYua8Y7h+xR6xwoeblxuXV37Sn5L5epMyxuEaogJOHRPqLAeJL88m50gibN1hI07CavkJ03kTdZSWnJ5MfhzJcdsGwCGXIFzmrc2cKMkwhu/AqopmOhKnJEhB8ax88/RsvTljDXE5QIkx7NFV8QZsWBDo+2RtAqKHZlZc6rBxJCFOnHOZqtVgduJ/u8/6ySaaCfKk38zXyzLIMi3JbaHmFUCKxIxMmSAgTbDY/2b/NDQOxCMVm9+syzx3Ie9n9s4KtFxdw51x7GdNR4o1wKlJhljQHTmm9R4LsW5SIccDVKCKILzVsgETsVC6zpSpHLgbMmzGTmOwCyHtqabW9QE2VtW4iyZNZbLl4SH2JygqbXAxxkjLWV7t38RVx2NG6TNmMhE0qZKoePfv/LJ8SQgO+Lw=
