language: node_js
branches:
    only:
        - develop
node_js:
    - '10'
before_script:
    - chmod +x ./scripts/deploy.sh
script: './scripts/deploy.sh'
deploy:
    provider: pages
    skip_cleanup: true
    keep_history: false
    local_dir: tmp
    on:
        branch: develop
env:
    global:
        secure: F96fm6XY4NvyTW+aGztJeq5PQLjzRllYIpJ0dA9R/FgMBc0eqgXO0Thg/u1rvqfPJNxn+ZkDg19QPz9EIUi381jO9M37tsJrUclF5DK/516LJhZFmKPDTKoN30TWDvx2W16DFW9en2FBwZbPJwh9/Zh/QXABpLY5SAoLPNRGv7QbYcrRoXej8mA2IbBEg9qpgh3E3zDr63AvpznnXBaiOL0ohpZ1mLFzrOYlmza9WUhFp5UG05PBuSypdGwILEeTNOhSnb5IKKSjBAymqa63lPsFfQGJbNY4MqlRssMv4ib6uc/Zne1CVgFqkU13k+jXV1vnGkWy+s4sa7kiJt7/GgJad5y29Wwf8F78fiehe5+d0KKriBPtaB15oE/lwiItWrOIrlxKvbbUd4ytJALL2dKUsM/X3jH22s5ruD0iKOgJ1NGf2AZ9sAJFwKejB4z7gxSOpqcAbdJUp/ZEGlKf8g6yGd2k/lTXdSWgy1evHDzmkcrpmdJKXkVgnTerBNSaXJg5HY/9G3+MmHzm++D3ut55oEz5+ZL//o5accngbdqBJRoiEBYJPk2nAuc5CEAdj4PgCYqIGN6VhPZcl/YGZpiaCIiGRg5pxveFmboEepYMQUjp5vlmWR0h1GTyYMG35g/GLrsYqTC9c8JEfn9DZcIyo9uWWj5fTH4Kr+VQ3/o=
